### ISSUE TITLE
Rename repositories 

### ISSUE THREAD

**Issue by imenesesl** [micardona96/MGL-STORE-FRONT#1]
Para llevar orden de los diferentes repositorios asociados al proyecto ``MGL-STORE`` se recomienda renombrarlos bajo el siguiente TAG.

``MGL-STORE-<LAYER>``.

Por ``LAYER`` se hace referencia a la capa del sistema. e.g. FRONT_END ó BACK_END

**Comment by imenesesl** [comment]
Por favor agregar a @tavo1998 👍

**Comment by imenesesl** [comment]
no cerrar este issue hasta que @avo1998 haya leído y echo los cambios anteriormente nombrados.

**Comment by tavo1998** [comment]
Cambios realizados en el backend.

**Comment by micardona96** [comment]
Es mejor tener solo un repositorio con dos carpetas front y back

**Comment by imenesesl** [comment]
@micardona96 hay que tener en cuenta que son dos estructuras totalmente diferentes, un  retroceso en uno de los proyecto implica retroceder en todos los documentos.
El control de versiones se debe hacer para cada proyecto de manera independiente, de tal forma que sea fácil y seguro navegar entre las diferentes ramas del mismo.
dando respuesta a tu comentario, la respuesta es un NO!, no podemos hacer eso.
